- name: Install this role on {{ansible_os_family}}
  include: "{{ansible_os_family}}.yml"


- name: Create an network for all application
  shell: docker network create {{tools_addnetwork}}
  failed_when: False

- name: Get Docker Gateway
  shell: ip route show | grep docker0 | awk '{print $9}'
  register: tools_docker_gateway
    
- name: Install Docker applications
  include: apps.yml tools_appname="{{tools_applications_item}}"
  loop: "{{tools_applications}}"
  loop_control:
    loop_var: tools_applications_item
  when: tools_applications is defined and tools_applications is not none and tools_applications != ""
  
- name: copy script files to remote
  copy: src=check_app_service.sh dest=/tmp/check_app_service.sh

- name: Check dockerapp service
  shell: bash /tmp/check_app_service.sh
  register: check_app_service
  notify: check_app_service


