- name: Install this role on {{ansible_os_family}}
  include: "{{ansible_os_family}}.yml"

- name: Install Docker applications
  include: apps.yml tools_appname="{{tools_applications_item}}"
  loop: "{{tools_applications}}"
  loop_control:
    loop_var: tools_applications_item
  when: tools_applications is defined and tools_applications is not none and tools_applications != ""
  
- name: copy script files to remote
  copy: src=check_dockerapp_service.sh dest=/tmp/check_dockerapp_service.sh

- name: Check dockerapp service
  shell: bash /tmp/check_dockerapp_service.sh
  register: check_dockerapp_service
  notify: check_dockerapp_service


