# refer to: https://hub.docker.com/_/mongo-express

version: "2.2"
services:
  mongoexpress:
      image: mongo-express
      container_name: "{{tools_appname}}"
      environment:
       - ME_CONFIG_BASICAUTH_USERNAME='admin'
       - ME_CONFIG_BASICAUTH_PASSWORD='admin123'
       - ME_CONFIG_MONGODB_SERVER={{tools_docker_gateway.stdout}}
       - ME_CONFIG_MONGODB_ADMINUSERNAME=root
       - ME_CONFIG_MONGODB_ADMINPASSWORD=123456
      restart: always
      ports:
       - {{tools_apps_mongoexpress_port}}:8081

networks:
  default:
    external:
      name: "{{tools_addnetwork}}"
