# this comopose file can be running

version: '2.0'

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: "{{tools_appname}}"
    restart: always
    ports:
      - {{tools_apps_portainer_port}}:9000
    volumes:
      - "{{tools_apps_dir}}/{{docker_appname}}/portainer_data:/data"
      - /var/run/docker.sock:/var/run/docker.sock
      
networks:
  default:
    external:
      name: "{{tools_addnetwork}}"
