version: "2.2"
services:
  phpmyadmin:
      image: mrvautin/adminmongo
      container_name: "{{tools_appname}}"
      environment:
       - PORT=1234
       - local=en
       - HOST=0.0.0.0
      restart: always
      ports:
       - {{tools_apps_adminmongo_port}}:1234
      volumes:
       - "{{tools_apps_dir}}/{{tools_appname}}/config:/config"

networks:
  default:
    external:
      name: "{{tools_addnetwork}}"
