# linuxserver/code-server is more suitable for Coder who is official image
# refer to: https://hub.docker.com/r/linuxserver/code-server
# project dir is /config/workspace

version: "2.1"
services:
  codeserver:
      image: linuxserver/code-server
      container_name: "{{tools_appname}}"
      environment:
        - PUID={{docker_uid}}
        - PGID={{docker_uid}}
        - PASSWORD=123456 #optional
        #- SUDO_PASSWORD=123456 #optional
        #- PROXY_DOMAIN=code-server.my.domain #optional
      restart: always
      stdin_open: true
      tty: true
      network_mode: host
      ports:
        - {{tools_apps_codeserver_port}}:8443
      volumes:
        - "{{tools_apps_dir}}/{{tools_appname}}/config:/config"
networks:
  default:
    external:
      name: "{{tools_addnetwork}}"
