# refer to: https://helpcenter.onlyoffice.com/server/docker/document/docker-installation.aspx

version: '3'
services:
  onlyoffice-documentserver:
    container_name: "{{tools_appname}}"
    image: onlyoffice/documentserver:latest
    volumes:
      - "{{tools_apps_dir}}/{{tools_appname}}/logs:/var/log/onlyoffice"
      - "{{tools_apps_dir}}/{{tools_appname}}/data:/var/www/onlyoffice/Data"
      - "{{tools_apps_dir}}/{{tools_appname}}/fonts:/usr/share/fonts/truetype/custom"
      - "{{tools_apps_dir}}/{{tools_appname}}/forgotten:/var/lib/onlyoffice/documentserver/App_Data/cache/files/forgotten"
    stdin_open: true
    restart: always
    ports:
      - "{{tools_apps_onlyofficedocumentserver_port}}:80"
      
networks:
  default:
    external:
      name: "{{tools_addnetwork}}"
