# refer to: https://hub.docker.com/_/adminer/

version: "2.0"
services:
  adminer:
      image: adminer
      container_name: "{{tools_appname}}"
      environment:
       - ADMINER_DEFAULT_SERVER={{tools_docker_gateway.stdout}}
      restart: always
      ports:
       - {{tools_apps_adminer_port}}:8080

networks:
  default:
    external:
      name: "{{tools_addnetwork}}"
