version: "3.7"
services:
  phppgadmin:
    restart: always
    image: dpage/pgadmin4
    container_name: "{{tools_appname}}"
    ports:
      - "{{tools_apps_pgadmin_port}}:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=SuperSecret
      - PGADMIN_LISTEN_ADDRESS=0.0.0.0

networks:
  default:
    external:
      name: "{{tools_addnetwork}}"
