version: "3.7"
services:
  phppgadmin:
    restart: always
    image: dockage/phppgadmin
    container_name: "{{docker_appname}}"
    ports:
      - "{{docker_apps_phppgadmin_port}}:80"
    environment:
      - PHP_PG_ADMIN_SERVER_DESC=PostgreSQL
      - PHP_PG_ADMIN_SERVER_HOST={{docker_gateway.stdout}}
      
networks:
  default:
    external:
      name: "{{docker_addnetwork}}"
