version: "3.7"
services:
  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: "{{tools_appname}}"
      environment:
       - PMA_HOST={{tools_docker_gateway.stdout}}
       - PMA_PORT=3306
       - UPLOAD_LIMIT=20M
      restart: always
      ports:
       - {{tools_apps_phpmyadmin_port}}:80
      volumes:
       - "{{tools_apps_dir}}/{{tools_appname}}/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php"

networks:
  default:
    external:
      name: "{{tools_addnetwork}}"
